# -*- coding: utf-8 -*-
"""環境建置

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xFNNl7yAusrr1vuTOM8qye4EM5qo2CIK
"""

#simple linear regression
import pandas as pd
import matplotlib.pyplot as plt
from ipywidgets import interact

url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data.csv"
data = pd.read_csv(url)
# y = w * x + b
x = data["YearsExperience"]
y = data["Salary"]

def plot_pred(w, b):
  y_pred = w*x + b

  plt.title("Salary v.s. YearExp")
  plt.xlabel("YearExp")
  plt.ylabel("Salary")
  plt.xlim([0, 12])
  plt.ylim([-60, 140])
  plt.scatter(x, y, marker = "x", color = "red", label = "real")
  plt.plot(x, y_pred, color = "blue", label = "predict")
  plt.show()

interact(plot_pred, w = (-100, 100, 1), b = (-100, 100, 1))